# Generated by Django 5.1.7 on 2025-03-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('time_to_perform', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
